import SwiftUI
// import GuPTCore // The generated UniFFI Swift module

class EngineProvider: ObservableObject {
    @Published var engine: GuptEngine?
    
    func initializeEngine(dbPath: String, pin: String) {
        do {
            // In a real app, dbPath is retrieved from FileManager
            // Call the static initialize function generated by UniFFI
            self.engine = try GuptEngine.initialize(dbPath: dbPath, pin: pin)
            print("Gupt Engine successfully initialized via UniFFI")
        } catch {
            print("Failed to initialize Gupt Engine: \(error)")
        }
    }
}
